//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTC.SharePoint.Evolution.AppResourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SPEvoContents {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SPEvoContents() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FTC.SharePoint.Evolution.AppResourses.SPEvoContents", typeof(SPEvoContents).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действия.
        /// </summary>
        internal static string Administration_ActionTitle {
            get {
                return ResourceManager.GetString("Administration_ActionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите сборку.
        /// </summary>
        internal static string Administration_AssemblyToLoad {
            get {
                return ResourceManager.GetString("Administration_AssemblyToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить.
        /// </summary>
        internal static string Administration_Discard {
            get {
                return ResourceManager.GetString("Administration_Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запуск.
        /// </summary>
        internal static string Administration_ExecuteEvolutionButtonTitle {
            get {
                return ResourceManager.GetString("Administration_ExecuteEvolutionButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для того чтобы откатиться на предыдущую эволюцию используйте таблицу. Для того чтобы актуализировать версию схемы, активируйте фичу, содержащую эволюции. .
        /// </summary>
        internal static string Administration_Info {
            get {
                return ResourceManager.GetString("Administration_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint Evolution - Администрирование.
        /// </summary>
        internal static string Administration_MainTitle {
            get {
                return ResourceManager.GetString("Administration_MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия.
        /// </summary>
        internal static string Administration_VersionTitle {
            get {
                return ResourceManager.GetString("Administration_VersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите версию.
        /// </summary>
        internal static string Administration_VersionToEvolution {
            get {
                return ResourceManager.GetString("Administration_VersionToEvolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущее состояние схемы SharePoint Evolution.
        /// </summary>
        internal static string AppliedPageAction_Description {
            get {
                return ResourceManager.GetString("AppliedPageAction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint Evolution.
        /// </summary>
        internal static string AppliedPageAction_Title {
            get {
                return ResourceManager.GetString("AppliedPageAction_Title", resourceCulture);
            }
        }
    }
}
